=== felixdittrich92/XML_project/xml/schema.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT weather_data (observation)>
<!ATTLIST weather_data
  xmlns CDATA #FIXED ''>

<!ELEMENT observation (date,temperature,solar_radiation,humidity)>
<!ATTLIST observation
  xmlns CDATA #FIXED ''>

<!ELEMENT date (LST_DATE,LST_TIME)>
<!ATTLIST date
  xmlns CDATA #FIXED ''>

<!ELEMENT temperature (T_CALC,T_HR_AVG,T_MAX,T_MIN,
                       infrared_surface_temperature,soil_temperature)>
<!ATTLIST temperature
  xmlns CDATA #FIXED ''>

<!ELEMENT solar_radiation (SOLARAD,SOLARAD_MAX,SOLARAD_MIN)>
<!ATTLIST solar_radiation
  xmlns CDATA #FIXED ''>

<!ELEMENT humidity (air_humidity,earth_humidity)>
<!ATTLIST humidity
  xmlns CDATA #FIXED ''>

<!ELEMENT LST_DATE (#PCDATA)>
<!ATTLIST LST_DATE
  xmlns CDATA #FIXED ''>

<!ELEMENT LST_TIME (#PCDATA)>
<!ATTLIST LST_TIME
  xmlns CDATA #FIXED ''>

<!ELEMENT T_CALC (#PCDATA)>
<!ATTLIST T_CALC
  xmlns CDATA #FIXED ''>

<!ELEMENT T_HR_AVG (#PCDATA)>
<!ATTLIST T_HR_AVG
  xmlns CDATA #FIXED ''>

<!ELEMENT T_MAX (#PCDATA)>
<!ATTLIST T_MAX
  xmlns CDATA #FIXED ''>

<!ELEMENT T_MIN (#PCDATA)>
<!ATTLIST T_MIN
  xmlns CDATA #FIXED ''>

<!ELEMENT infrared_surface_temperature (SUR_TEMP,SUR_TEMP_MAX,
                                        SUR_TEMP_MIN)>
<!ATTLIST infrared_surface_temperature
  xmlns CDATA #FIXED ''>

<!ELEMENT soil_temperature (SOIL_TEMP_5,SOIL_TEMP_10)>
<!ATTLIST soil_temperature
  xmlns CDATA #FIXED ''>

<!ELEMENT SOLARAD (#PCDATA)>
<!ATTLIST SOLARAD
  xmlns CDATA #FIXED ''>

<!ELEMENT SOLARAD_MAX (#PCDATA)>
<!ATTLIST SOLARAD_MAX
  xmlns CDATA #FIXED ''>

<!ELEMENT SOLARAD_MIN (#PCDATA)>
<!ATTLIST SOLARAD_MIN
  xmlns CDATA #FIXED ''>

<!ELEMENT air_humidity (RH_HR_AVG)>
<!ATTLIST air_humidity
  xmlns CDATA #FIXED ''>

<!ELEMENT earth_humidity (SOIL_MOISTURE_5,SOIL_MOISTURE_10)>
<!ATTLIST earth_humidity
  xmlns CDATA #FIXED ''>

<!ELEMENT SUR_TEMP (#PCDATA)>
<!ATTLIST SUR_TEMP
  xmlns CDATA #FIXED ''>

<!ELEMENT SUR_TEMP_MAX (#PCDATA)>
<!ATTLIST SUR_TEMP_MAX
  xmlns CDATA #FIXED ''>

<!ELEMENT SUR_TEMP_MIN (#PCDATA)>
<!ATTLIST SUR_TEMP_MIN
  xmlns CDATA #FIXED ''>

<!ELEMENT SOIL_TEMP_5 (#PCDATA)>
<!ATTLIST SOIL_TEMP_5
  xmlns CDATA #FIXED ''>

<!ELEMENT SOIL_TEMP_10 (#PCDATA)>
<!ATTLIST SOIL_TEMP_10
  xmlns CDATA #FIXED ''>

<!ELEMENT RH_HR_AVG (#PCDATA)>
<!ATTLIST RH_HR_AVG
  xmlns CDATA #FIXED ''>

<!ELEMENT SOIL_MOISTURE_5 (#PCDATA)>
<!ATTLIST SOIL_MOISTURE_5
  xmlns CDATA #FIXED ''>

<!ELEMENT SOIL_MOISTURE_10 (#PCDATA)>
<!ATTLIST SOIL_MOISTURE_10
  xmlns CDATA #FIXED ''>

=== felixdittrich92/XML_project/Abgabe/Visualisierungen/tagesdiagramm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE weather_data SYSTEM "schema.dtd">
<?xml-stylesheet href="tagesdiagramm.xsl" type="text/xsl" ?>
<weather_data>
   <observation>
       <date>
           <LST_DATE>20180101</LST_DATE>
           <LST_TIME>0</LST_TIME>
       </date>
       <temperature>
           <T_CALC>-12.9</T_CALC>
           <T_HR_AVG>-12.5</T_HR_AVG>
           <T_MAX>-12.0</T_MAX>
           <T_MIN>-12.9</T_MIN>
           <infrared_surface_temperature>
               <SUR_TEMP>-11.9</SUR_TEMP>
               <SUR_TEMP_MAX>-11.4</SUR_TEMP_MAX>
               <SUR_TEMP_MIN>-12.4</SUR_TEMP_MIN>
           </infrared_surface_temperature>
           <soil_temperature>
               <SOIL_TEMP_5>1.0</SOIL_TEMP_5>
               <SOIL_TEMP_10>1.7</SOIL_TEMP_10>
           </soil_temperature>
       </temperature>
       <solar_radiation>
           <SOLARAD>0</SOLARAD>
           <SOLARAD_MAX>0</SOLARAD_MAX>
           <SOLARAD_MIN>0</SOLARAD_MIN>
       </solar_radiation>
       <humidity>
           <air_humidity>
               <RH_HR_AVG>65</RH_HR_AVG>
           </air_humidity>
           <earth_humidity>
               <SOIL_MOISTURE_5>0.321</SOIL_MOISTURE_5>
               <SOIL_MOISTURE_10>0.322</SOIL_MOISTURE_10>
           </earth_humidity>
       </humidity>
   </observation>
   <observation>
       <date>
           <LST_DATE>20180101</LST_DATE>
           <LST_TIME>100</LST_TIME>
       </date>
       <temperature>
           <T_CALC>-13.4</T_CALC>
           <T_HR_AVG>-13.2</T_HR_AVG>
           <T_MAX>-12.9</T_MAX>
           <T_MIN>-13.5</T_MIN>
           <infrared_surface_temperature>
               <SUR_TEMP>-12.6</SUR_TEMP>
               <SUR_TEMP_MAX>-12.4</SUR_TEMP_MAX>
               <SUR_TEMP_MIN>-12.9</SUR_TEMP_MIN>
           </infrared_surface_temperature>
           <soil_temperature>
               <SOIL_TEMP_5>0.9</SOIL_TEMP_5>
               <SOIL_TEMP_10>1.7</SOIL_TEMP_10>
           </soil_temperature>
       </temperature>
       <solar_radiation>
           <SOLARAD>0</SOLARAD>
           <SOLARAD_MAX>0</SOLARAD_MAX>
           <SOLARAD_MIN>0</SOLARAD_MIN>
       </solar_radiation>
       <humidity>
           <air_humidity>
               <RH_HR_AVG>68</RH_HR_AVG>
           </air_humidity>
           <earth_humidity>
               <SOIL_MOISTURE_5>0.322</SOIL_MOISTURE_5>
               <SOIL_MOISTURE_10>0.32299999999999995</SOIL_MOISTURE_10>
           </earth_humidity>
       </humidity>
   </observation>
   <observation>
       <date>
           <LST_DATE>20180101</LST_DATE>
           <LST_TIME>200</LST_TIME>
       </date>
       <temperature>
           <T_CALC>-14.3</T_CALC>
           <T_HR_AVG>-13.7</T_HR_AVG>
           <T_MAX>-13.2</T_MAX>
           <T_MIN>-14.3</T_MIN>
           <infrared_surface_temperature>
               <SUR_TEMP>-12.9</SUR_TEMP>
               <SUR_TEMP_MAX>-12.5</SUR_TEMP_MAX>
               <SUR_TEMP_MIN>-13.3</SUR_TEMP_MIN>
           </infrared_surface_temperature>
           <soil_temperature>
               <SOIL_TEMP_5>0.9</SOIL_TEMP_5>
               <SOIL_TEMP_10>1.6</SOIL_TEMP_10>
           </soil_temperature>
       </temperature>
       <solar_radiation>
           <SOLARAD>0</SOLARAD>
           <SOLARAD_MAX>0</SOLARAD_MAX>
           <SOLARAD_MIN>0</SOLARAD_MIN>
       </solar_radiation>
       <humidity>
           <air_humidity>
               <RH_HR_AVG>70</RH_HR_AVG>
           </air_humidity>
           <earth_humidity>
               <SOIL_MOISTURE_5>0.32299999999999995</SOIL_MOISTURE_5>
               <SOIL_MOISTURE_10>0.322</SOIL_MOISTURE_10>
           </earth_humidity>
       </humidity>
   </observation>
   <observation>
       <date>
           <LST_DATE>20180101</LST_DATE>
           <LST_TIME>300</LST_TIME>
       </date>
       <temperature>
           <T_CALC>-15.4</T_CALC>
           <T_HR_AVG>-14.9</T_HR_AVG>
           <T_MAX>-14.3</T_MAX>
           <T_MIN>-15.4</T_MIN>
           <infrared_surface_temperature>
               <SUR_TEMP>-13.7</SUR_TEMP>
               <SUR_TEMP_MAX>-13.3</SUR_TEMP_MAX>
               <SUR_TEMP_MIN>-14.0</SUR_TEMP_MIN>
           </infrared_surface_temperature>
           <soil_temperature>
               <SOIL_TEMP_5>0.9</SOIL_TEMP_5>
               <SOIL_TEMP_10>1.6</SOIL_TEMP_10>
           </soil_temperature>
       </temperature>
       <solar_radiation>
           <SOLARAD>0</SOLARAD>
           <SOLARAD_MAX>0</SOLARAD_MAX>
           <SOLARAD_MIN>0</SOLARAD_MIN>
       </solar_radiation>
       <humidity>
           <air_humidity>
               <RH_HR_AVG>76</RH_HR_AVG>
           </air_humidity>
           <earth_humidity>
               <SOIL_MOISTURE_5>0.324</SOIL_MOISTURE_5>
               <SOIL_MOISTURE_10>0.322</SOIL_MOISTURE_10>
           </earth_humidity>
       </humidity>
   </observation>
   <observation>
       <date>
           <LST_DATE>20180101</LST_DATE>
           <LST_TIME>400</LST_TIME>
       </date>
       <temperature>
           <T_CALC>-15.7</T_CALC>
           <T_HR_AVG>-15.5</T_HR_AVG>
           <T_MAX>-15.3</T_MAX>
           <T_MIN>-15.8</T_MIN>
           <infrared_surface_temperature>
               <SUR_TEMP>-14.2</SUR_TEMP>
               <SUR_TEMP_MAX>-13.9</SUR_TEMP_MAX>
               <SUR_TEMP_MIN>-14.6</SUR_TEMP_MIN>
           </infrared_surface_temperature>
           <soil_temperature>
               <SOIL_TEMP_5>0.8</SOIL_TEMP_5>
               <SOIL_TEMP_10>1.6</SOIL_TEMP_10>
           </soil_temperature>
       </temperature>
       <solar_radiation>
           <SOLARAD>0</SOLARAD>
           <SOLARAD_MAX>0</SOLARAD_MAX>
           <SOLARAD_MIN>0</SOLARAD_MIN>
       </solar_radiation>
       <humidity>
           <air_humidity>
               <RH_HR_AVG>78</RH_HR_AVG>
           </air_humidity>
           <earth_humidity>
               <SOIL_MOISTURE_5>0.322</SOIL_MOISTURE_5>
               <SOIL_MOISTURE_10>0.321</SOIL_MOISTURE_10>
           </earth_humidity>
       </humidity>
   </observation>
   <observation>
       <date>
           <LST_DATE>20180101</LST_DATE>
           <LST_TIME>500</LST_TIME>
       </date>
       <temperature>
           <T_CALC>-15.9</T_CALC>
           <T_HR_AVG>-16.0</T_HR_AVG>
           <T_MAX>-15.8</T_MAX>
           <T_MIN>-16.2</T_MIN>
           <infrared_surface_temperature>
               <SUR_TEMP>-14.4</SUR_TEMP>
               <SUR_TEMP_MAX>-13.0</SUR_TEMP_MAX>
               <SUR_TEMP_MIN>-14.8</SUR_TEMP_MIN>
           </infrared_surface_temperature>
           <soil_temperature>
               <SOIL_TEMP_5>0.8</SOIL_TEMP_5>
               <SOIL_TEMP_10>1.5</SOIL_TEMP_10>
           </soil_temperature>
       </temperature>
       <solar_radiation>
           <SOLARAD>0</SOLARAD>
           <SOLARAD_MAX>0</SOLARAD_MAX>
           <SOLARAD_MIN>0</SOLARAD_MIN>
       </solar_radiation>
       <humidity>
           <air_humidity>
               <RH_HR_AVG>78</RH_HR_AVG>
           </air_humidity>
           <earth_humidity>
               <SOIL_MOISTURE_5>0.321</SOIL_MOISTURE_5>
               <SOIL_MOISTURE_10>0.321</SOIL_MOISTURE_10>
           </earth_humidity>
       </humidity>
   </observation>
   <observation>
       <date>
           <LST_DATE>20180101</LST_DATE>
           <LST_TIME>600</LST_TIME>
       </date>
       <temperature>
           <T_CALC>-16.5</T_CALC>
           <T_HR_AVG>-16.2</T_HR_AVG>
           <T_MAX>-15.9</T_MAX>
           <T_MIN>-16.5</T_MIN>
           <infrared_surface_temperature>
               <SUR_TEMP>-13.6</SUR_TEMP>
               <SUR_TEMP_MAX>-13.0</SUR_TEMP_MAX>
               <SUR_TEMP_MIN>-14.8</SUR_TEMP_MIN>
           </infrared_surface_temperature>
           <soil_temperature>
               <SOIL_TEMP_5>0.7</SOIL_TEMP_5>
               <SOIL_TEMP_10>1.5</SOIL_TEMP_10>
           </soil_temperature>
       </temperature>
       <solar_radiation>
           <SOLARAD>0</SOLARAD>
           <SOLARAD_MAX>0</SOLARAD_MAX>
           <SOLARAD_MIN>0</SOLARAD_MIN>
       </solar_radiation>
       <humidity>
           <air_humidity>
               <RH_HR_AVG>77</RH_HR_AVG>
           </air_humidity>
           <earth_humidity>
               <SOIL_MOISTURE_5>0.317</SOIL_MOISTURE_5>
               <SOIL_MOISTURE_10>0.321</SOIL_MOISTURE_10>
           </earth_humidity>
       </humidity>
   </observation>
   <observation>
       <date>
           <LST_DATE>20180101</LST_DATE>
           <LST_TIME>700</LST_TIME>
       </date>
       <temperature>
           <T_CALC>-16.8</T_CALC>
           <T_HR_AVG>-16.7</T_HR_AVG>
           <T_MAX>-16.5</T_MAX>
           <T_MIN>-16.8</T_MIN>
           <infrared_surface_temperature>
               <SUR_TEMP>-15.0</SUR_TEMP>
               <SUR_TEMP_MAX>-14.8</SUR_TEMP_MAX>
               <SUR_TEMP_MIN>-15.3</SUR_TEMP_MIN>
           </infrared_surface_temperature>
           <soil_temperature>
               <SOIL_TEMP_5>0.7</SOIL_TEMP_5>
               <SOIL_TEMP_10>1.5</SOIL_TEMP_10>
           </soil_temperature>
       </temperature>
       <solar_radiation>
           <SOLARAD>0</SOLARAD>
           <SOLARAD_MAX>0</SOLARAD_MAX>
           <SOLARAD_MIN>0</SOLARAD_MIN>
       </solar_radiation>
       <humidity>
           <air_humidity>
               <RH_HR_AVG>77</RH_HR_AVG>
           </air_humidity>
           <earth_humidity>
               <SOIL_MOISTURE_5>0.316</SOIL_MOISTURE_5>
               <SOIL_MOISTURE_10>0.319</SOIL_MOISTURE_10>
           </earth_humidity>
       </humidity>
   </observation>
   <observation>
       <date>
           <LST_DATE>20180101</LST_DATE>
           <LST_TIME>800</LST_TIME>
       </date>
       <temperature>
           <T_CALC>-16.2</T_CALC>
           <T_HR_AVG>-16.6</T_HR_AVG>
           <T_MAX>-16.2</T_MAX>
           <T_MIN>-16.9</T_MIN>
           <infrared_surface_temperature>
               <SUR_TEMP>-14.1</SUR_TEMP>
               <SUR_TEMP_MAX>-12.9</SUR_TEMP_MAX>
               <SUR_TEMP_MIN>-15.0</SUR_TEMP_MIN>
